### ISSUE TITLE
DDP is 4 times slower in my case

### ISSUE THREAD

**Issue by shamsbasir** [The-AI-Summer/pytorch-ddp#1]
I tried to replicate your experiments on a machine with 4 GPUs. Unfortunately my DDP is 4 times slower. I was wondering if you have any pointers as to what could be the reason.

**Comment by black0017** [comment]
That's unexpected. 

1) Slower compare to single gpu, right?

2) How many workers are you using in the dataloader?

3) Can you share your hardware, something like the outputs of `nvidia-smi` and `lscpu`.

**Comment by shamsbasir** [comment]
Thank you for helping. 

1) yes compared to a single gpu. 
2) my workers are the same as is in your codes. 

3) my GPUs 
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.65.01    Driver Version: 515.65.01    CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-PCIE...  On   | 00000000:3B:00.0 Off |                    0 |
| N/A   34C    P0    29W / 250W |      0MiB / 32768MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-PCIE...  On   | 00000000:5E:00.0 Off |                    0 |
| N/A   35C    P0    27W / 250W |      0MiB / 32768MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-PCIE...  On   | 00000000:AF:00.0 Off |                    0 |
| N/A   32C    P0    25W / 250W |      0MiB / 32768MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-PCIE...  On   | 00000000:D8:00.0 Off |                    0 |
| N/A   33C    P0    27W / 250W |      0MiB / 32768MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage
|
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+



Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                24
On-line CPU(s) list:   0-23
Thread(s) per core:    1
Core(s) per socket:    12
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz
Stepping:              4
CPU MHz:               2601.000
CPU max MHz:           2601.0000
CPU min MHz:           1000.0000
BogoMIPS:              5200.00
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              19712K
NUMA node0 CPU(s):     0-11
NUMA node1 CPU(s):     12-23

**Comment by black0017** [comment]
Hi @shamsbasir ,

Since you have 24 cpus, you probably have a cpu bottleneck.

Can you try with `num_workers=6`?

6 is the ratio between `#cpus/#gpus =24/4 = 6` in your case.

**Comment by shamsbasir** [comment]
Hello @black0017, 
I did change the num_workers=6 for the single gpu and the ddp but the results are the same. 

**for a single GPU:**  Total elapsed time: 27.71 seconds,      **Train 1 epoch 21.03 seconds**

**for 4 GPUs :** Total elapsed time: 172.43 seconds,      **Train 1 epoch 134.59 seconds**

**Comment by black0017** [comment]
I see that the batch size is 256 in my script. In the DDP case, this is the batch size per GPU.

Maybe if you try `batch size = 256// 4 ` (since you have 4 GPUs) ?

This will offload some work from your dataloaders if that is the problem.

I would also try using 2 GPUS with DDP and see if I could get a speedup (with num_workers=6 ), both with batch_size =256 and batch size = 128 (this is again per GPU)

Let me know how it works out!
